<?php
/**
 * AdPublicationAdPublicationRead
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Ubiflow\Model;

use \ArrayAccess;
use \Ubiflow\ObjectSerializer;

/**
 * AdPublicationAdPublicationRead Class Doc Comment
 *
 * @category Class
 * @description An AdPublication represents the current state of the publication of an ad for a portal.
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdPublicationAdPublicationRead implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AdPublication-ad_publication.read';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'ad' => '\Ubiflow\Model\AdAdPublicationRead',
        'advertiserPublication' => '\Ubiflow\Model\AdvertiserPublicationAdPublicationRead',
        'selected' => 'bool',
        'publishable' => 'bool',
        'publicationIncompatibilities' => '\Ubiflow\Model\AdPublicationIncompatibilityAdPublicationRead[]',
        'lastPublishedAt' => '\DateTime',
        'unPublishedAt' => '\DateTime',
        'urlOnPortal' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'ad' => null,
        'advertiserPublication' => null,
        'selected' => null,
        'publishable' => null,
        'publicationIncompatibilities' => null,
        'lastPublishedAt' => 'date-time',
        'unPublishedAt' => 'date-time',
        'urlOnPortal' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'ad' => 'ad',
        'advertiserPublication' => 'advertiserPublication',
        'selected' => 'selected',
        'publishable' => 'publishable',
        'publicationIncompatibilities' => 'publicationIncompatibilities',
        'lastPublishedAt' => 'lastPublishedAt',
        'unPublishedAt' => 'unPublishedAt',
        'urlOnPortal' => 'urlOnPortal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'ad' => 'setAd',
        'advertiserPublication' => 'setAdvertiserPublication',
        'selected' => 'setSelected',
        'publishable' => 'setPublishable',
        'publicationIncompatibilities' => 'setPublicationIncompatibilities',
        'lastPublishedAt' => 'setLastPublishedAt',
        'unPublishedAt' => 'setUnPublishedAt',
        'urlOnPortal' => 'setUrlOnPortal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'ad' => 'getAd',
        'advertiserPublication' => 'getAdvertiserPublication',
        'selected' => 'getSelected',
        'publishable' => 'getPublishable',
        'publicationIncompatibilities' => 'getPublicationIncompatibilities',
        'lastPublishedAt' => 'getLastPublishedAt',
        'unPublishedAt' => 'getUnPublishedAt',
        'urlOnPortal' => 'getUrlOnPortal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['ad'] = isset($data['ad']) ? $data['ad'] : null;
        $this->container['advertiserPublication'] = isset($data['advertiserPublication']) ? $data['advertiserPublication'] : null;
        $this->container['selected'] = isset($data['selected']) ? $data['selected'] : null;
        $this->container['publishable'] = isset($data['publishable']) ? $data['publishable'] : null;
        $this->container['publicationIncompatibilities'] = isset($data['publicationIncompatibilities']) ? $data['publicationIncompatibilities'] : null;
        $this->container['lastPublishedAt'] = isset($data['lastPublishedAt']) ? $data['lastPublishedAt'] : null;
        $this->container['unPublishedAt'] = isset($data['unPublishedAt']) ? $data['unPublishedAt'] : null;
        $this->container['urlOnPortal'] = isset($data['urlOnPortal']) ? $data['urlOnPortal'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The unique identifier of the ad publication, in the Ubiflow IS.
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets ad
     *
     * @return \Ubiflow\Model\AdAdPublicationRead
     */
    public function getAd()
    {
        return $this->container['ad'];
    }

    /**
     * Sets ad
     *
     * @param \Ubiflow\Model\AdAdPublicationRead $ad ad
     *
     * @return $this
     */
    public function setAd($ad)
    {
        $this->container['ad'] = $ad;

        return $this;
    }

    /**
     * Gets advertiserPublication
     *
     * @return \Ubiflow\Model\AdvertiserPublicationAdPublicationRead
     */
    public function getAdvertiserPublication()
    {
        return $this->container['advertiserPublication'];
    }

    /**
     * Sets advertiserPublication
     *
     * @param \Ubiflow\Model\AdvertiserPublicationAdPublicationRead $advertiserPublication advertiserPublication
     *
     * @return $this
     */
    public function setAdvertiserPublication($advertiserPublication)
    {
        $this->container['advertiserPublication'] = $advertiserPublication;

        return $this;
    }

    /**
     * Gets selected
     *
     * @return bool
     */
    public function getSelected()
    {
        return $this->container['selected'];
    }

    /**
     * Sets selected
     *
     * @param bool $selected Indicates weather the ad has been selected by the advertiser to be published.  Note that the fact that an ad is selected does NOT guarantee that it will be published, for multiple reasons :  - It may not be publishable (or may become unpublishable after an update).  - The advertiser has a quota (maximum number of ads) for this portal. In this case :      - If the advertiser publication is configured to be automatic (thus not manual),        the selection of ads is not taken into account :        in other terms, the \"selected\" boolean has no effect.      - If the advertiser publication is configured to be manual,        Ubiflow send the maximum number of ads until the quota is reached.  - The portal may refuse to publish the ad, for reasons that belong to it :      - It has a moderation tool, and moderators judged that the ad is not convenient.      - There is currently a litigation between the portal and the advertiser.
     *
     * @return $this
     */
    public function setSelected($selected)
    {
        $this->container['selected'] = $selected;

        return $this;
    }

    /**
     * Gets publishable
     *
     * @return bool
     */
    public function getPublishable()
    {
        return $this->container['publishable'];
    }

    /**
     * Sets publishable
     *
     * @param bool $publishable Indicates weather the ad may be published on the portal.  When the ad is not publishable on the portal, the reasons are indicated in the dedicated property \"publicationIncompatibilities\".  Note that a publishable ad will NOT always be published. Either because it is not selected, or for many other reasons (for more details, see the comments on the \"selected\" property).
     *
     * @return $this
     */
    public function setPublishable($publishable)
    {
        $this->container['publishable'] = $publishable;

        return $this;
    }

    /**
     * Gets publicationIncompatibilities
     *
     * @return \Ubiflow\Model\AdPublicationIncompatibilityAdPublicationRead[]
     */
    public function getPublicationIncompatibilities()
    {
        return $this->container['publicationIncompatibilities'];
    }

    /**
     * Sets publicationIncompatibilities
     *
     * @param \Ubiflow\Model\AdPublicationIncompatibilityAdPublicationRead[] $publicationIncompatibilities The collection of all reasons why the ad may not be published on the portal.
     *
     * @return $this
     */
    public function setPublicationIncompatibilities($publicationIncompatibilities)
    {
        $this->container['publicationIncompatibilities'] = $publicationIncompatibilities;

        return $this;
    }

    /**
     * Gets lastPublishedAt
     *
     * @return \DateTime
     */
    public function getLastPublishedAt()
    {
        return $this->container['lastPublishedAt'];
    }

    /**
     * Sets lastPublishedAt
     *
     * @param \DateTime $lastPublishedAt The date the ad was published (ie sent by Ubiflow to the portal) for the last time.  This date is null if the ad has been unpublished.  Dates use the <a href=\"https://tools.ietf.org/html/rfc3339#section-5.8\">RFC3339</a> format (ex: 2020-12-16T00:00:00+00).
     *
     * @return $this
     */
    public function setLastPublishedAt($lastPublishedAt)
    {
        $this->container['lastPublishedAt'] = $lastPublishedAt;

        return $this;
    }

    /**
     * Gets unPublishedAt
     *
     * @return \DateTime
     */
    public function getUnPublishedAt()
    {
        return $this->container['unPublishedAt'];
    }

    /**
     * Sets unPublishedAt
     *
     * @param \DateTime $unPublishedAt The date the ad was unpublished (ie Ubiflow sent an order to the portal to remove its publication).  This date is null if the ad is currently published.  Dates use the <a href=\"https://tools.ietf.org/html/rfc3339#section-5.8\">RFC3339</a> format (ex: 2020-12-16T00:00:00+00).
     *
     * @return $this
     */
    public function setUnPublishedAt($unPublishedAt)
    {
        $this->container['unPublishedAt'] = $unPublishedAt;

        return $this;
    }

    /**
     * Gets urlOnPortal
     *
     * @return string
     */
    public function getUrlOnPortal()
    {
        return $this->container['urlOnPortal'];
    }

    /**
     * Sets urlOnPortal
     *
     * @param string $urlOnPortal The url of the ad on the portal.  This property is defined only when the ad is currently published on the portal AND when the portal has communicated its url to Ubiflow. This is why you cannot entirely rely on this property to know if the ad is currently published.
     *
     * @return $this
     */
    public function setUrlOnPortal($urlOnPortal)
    {
        $this->container['urlOnPortal'] = $urlOnPortal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
