<?php
/**
 * AdPublicationAdPublicationReadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ubiflow;

use PHPUnit\Framework\TestCase;

/**
 * AdPublicationAdPublicationReadTest Class Doc Comment
 *
 * @category    Class
 * @description An AdPublication represents the current state of the publication of an ad for a portal.
 * @package     Ubiflow
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdPublicationAdPublicationReadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdPublicationAdPublicationRead"
     */
    public function testAdPublicationAdPublicationRead()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "ad"
     */
    public function testPropertyAd()
    {
    }

    /**
     * Test attribute "advertiserPublication"
     */
    public function testPropertyAdvertiserPublication()
    {
    }

    /**
     * Test attribute "selected"
     */
    public function testPropertySelected()
    {
    }

    /**
     * Test attribute "publishable"
     */
    public function testPropertyPublishable()
    {
    }

    /**
     * Test attribute "publicationIncompatibilities"
     */
    public function testPropertyPublicationIncompatibilities()
    {
    }

    /**
     * Test attribute "lastPublishedAt"
     */
    public function testPropertyLastPublishedAt()
    {
    }

    /**
     * Test attribute "unPublishedAt"
     */
    public function testPropertyUnPublishedAt()
    {
    }

    /**
     * Test attribute "urlOnPortal"
     */
    public function testPropertyUrlOnPortal()
    {
    }
}
