<?php
/**
 * AdvertiserPublicationAdvertiserPublicationReadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ubiflow;

use PHPUnit\Framework\TestCase;

/**
 * AdvertiserPublicationAdvertiserPublicationReadTest Class Doc Comment
 *
 * @category    Class
 * @description An AdvertiserPublication represents the current publication configuration of an advertiser for a portal.
 * @package     Ubiflow
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdvertiserPublicationAdvertiserPublicationReadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdvertiserPublicationAdvertiserPublicationRead"
     */
    public function testAdvertiserPublicationAdvertiserPublicationRead()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "advertiser"
     */
    public function testPropertyAdvertiser()
    {
    }

    /**
     * Test attribute "portal"
     */
    public function testPropertyPortal()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "maxNumberOfAds"
     */
    public function testPropertyMaxNumberOfAds()
    {
    }

    /**
     * Test attribute "adsSelectionConfiguration"
     */
    public function testPropertyAdsSelectionConfiguration()
    {
    }

    /**
     * Test attribute "lastPublicationDate"
     */
    public function testPropertyLastPublicationDate()
    {
    }
}
