<?php
/**
 * AdvertiserEmissionReportMessageJsonldFeedReportMessageReadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ubiflow;

use PHPUnit\Framework\TestCase;

/**
 * AdvertiserEmissionReportMessageJsonldFeedReportMessageReadTest Class Doc Comment
 *
 * @category    Class
 * @description An AdvertiserEmissionReportMessage is generated during an emission. It is a detailed message reporting an error or a warning.
 * @package     Ubiflow
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdvertiserEmissionReportMessageJsonldFeedReportMessageReadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdvertiserEmissionReportMessageJsonldFeedReportMessageRead"
     */
    public function testAdvertiserEmissionReportMessageJsonldFeedReportMessageRead()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "ad"
     */
    public function testPropertyAd()
    {
    }

    /**
     * Test attribute "feedReport"
     */
    public function testPropertyFeedReport()
    {
    }
}
