<?php
/**
 * AdvertiserEmissionReportJsonldFeedReportReadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ubiflow;

use PHPUnit\Framework\TestCase;

/**
 * AdvertiserEmissionReportJsonldFeedReportReadTest Class Doc Comment
 *
 * @category    Class
 * @description An AdvertiserEmissionReport is generated during an emission. It indicates to you the number of ads and pictures that have been processed during a publication and gives you a detailed report.
 * @package     Ubiflow
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdvertiserEmissionReportJsonldFeedReportReadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdvertiserEmissionReportJsonldFeedReportRead"
     */
    public function testAdvertiserEmissionReportJsonldFeedReportRead()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "advertiserEmission"
     */
    public function testPropertyAdvertiserEmission()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "startedAt"
     */
    public function testPropertyStartedAt()
    {
    }

    /**
     * Test attribute "endedAt"
     */
    public function testPropertyEndedAt()
    {
    }

    /**
     * Test attribute "adsResults"
     */
    public function testPropertyAdsResults()
    {
    }

    /**
     * Test attribute "picturesResults"
     */
    public function testPropertyPicturesResults()
    {
    }
}
