<?php
/**
 * InlineResponse2002Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ubiflow;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2002Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002
 * @package     Ubiflow
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2002"
     */
    public function testInlineResponse2002()
    {
    }

    /**
     * Test attribute "hydramember"
     */
    public function testPropertyHydramember()
    {
    }

    /**
     * Test attribute "hydratotalItems"
     */
    public function testPropertyHydratotalItems()
    {
    }

    /**
     * Test attribute "hydraview"
     */
    public function testPropertyHydraview()
    {
    }

    /**
     * Test attribute "hydrasearch"
     */
    public function testPropertyHydrasearch()
    {
    }
}
