<?php
/**
 * AdApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ubiflow;

use Ubiflow\Configuration;
use Ubiflow\ApiException;
use Ubiflow\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ubiflow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteAdItem
     *
     * Delete an Ad.
     *
     */
    public function testDeleteAdItem()
    {
    }

    /**
     * Test case for getAdCollection
     *
     * Retrieves a collection of Ads.
     *
     */
    public function testGetAdCollection()
    {
    }

    /**
     * Test case for getAdItem
     *
     * Retrieves an Ad.
     *
     */
    public function testGetAdItem()
    {
    }

    /**
     * Test case for postAdCollection
     *
     * Create an Ad.
     *
     */
    public function testPostAdCollection()
    {
    }

    /**
     * Test case for postAdCollection
     *
     * Create an Ad.
     *
     */
    public function testPostAdCollection()
    {
    }

    /**
     * Test case for putAdItem
     *
     * Update an Ad.
     *
     */
    public function testPutAdItem()
    {
    }

    /**
     * Test case for putAdItem
     *
     * Update an Ad.
     *
     */
    public function testPutAdItem()
    {
    }
}
